### ISSUE TITLE
Wrong keypoint position

### ISSUE THREAD

**Issue by HiiHongFe** [cure-lab/SmoothNet#11]
I'm sorry to disturb you again. I tried Yolo_ Pose predicted the key points and sent the predicted key points to smoothnet. I used the 2D key point model based on hrnet. In my opinion, the jitter problem has been reduced, but a large position offset problem has been found.
as follow：
![ea04038596de74b917e613503f4bd41f](https://user-images.githubusercontent.com/44940083/183560422-601b8849-9d36-43d0-9b51-8d1ccd3a358b.png)

**Comment by ailingzengzzz** [comment]
Hi @HiiHongFe ,

Which pretrained model did you use? Also, have you conducted position normalization via the height and width of the image?

**Comment by HiiHongFe** [comment]
> Hi @HiiHongFe ,
> 
> Which pretrained model did you use? Also, have you conducted position normalization via the height and width of the image?

@ailingzengzzz 

Thank you for your reply！ I use the pretrained  of human3.6m/hrnet.，window size is 32.  The key points I used have been restored to the size of the original image.

**Comment by HiiHongFe** [comment]
> Hi @HiiHongFe ,
> 
> Which pretrained model did you use? Also, have you conducted position normalization via the height and width of the image?

@ailingzengzzz 
![image](https://user-images.githubusercontent.com/44940083/183562789-9c769614-3932-4eb3-bbeb-fadb8f6845fa.png)

**Comment by HiiHongFe** [comment]
I try not to restore the key points to the original image, but there is also such an offset problem

**Comment by juxuan27** [comment]
Hi, @HiiHongFe !
We have double check that there does not exist an offset problem in our own datasets. Although I do not know the detail of your implementation. I recommend you to re-check the following parts:
- The translation of bbox coordinates and image coordinates, e.g. did you add the y value of bbox to x axis?
- The normalization of keypoints, e.g. did you normalize x and y to [0,1] instead of [-0.5,0.5]? Or did you use y/width instead of x/width(under the circumstance that x is the abscissa)?

**Comment by HiiHongFe** [comment]
Hi, @ailingzengzzz @juxuan27 
Thank you very much for your answers. I checked yesterday and found that the problem was normalization. I didn't normalize the key points well. Now the problem has been solved. Thank you!
