### ISSUE TITLE
About add more than 2 datasets  for training.

### ISSUE THREAD

**Issue by ligaoqi2** [cure-lab/SmoothNet#27]
When I wanna to add my h36m 2D dataset, I found "training_iter = min([len(self.train_dataloader[i]) for i in range(len(self.train_dataloader))])" in the lib.core.trainer.py -> line 100. 

I wonder if you want to add different dataset, why use min() not sum()?

Because if min(), the training will take the little dataset only.

**Comment by juxuan27** [comment]
Hi, @ligaoqi2 ! Thank you for your focus.
We use min() to make sure each dataset can be included in the training process evenly. This is because the big difference among dataset sizes may lead to distribution domination of the largest dataset (e.g. training on Human3.6M and 3DPW may lead to distribution domination of Human3.6M).
You can change the union training setting to sum() instead of mean() if it can lead to better results on your dataset. We are looking forward to your feedback and future discussion.
