### ISSUE TITLE
radar target trajectory filtering

### ISSUE THREAD

**Issue by jiejiangd** [cure-lab/SmoothNet#3]
I would like to ask whether this method is feasible if it is used for radar target trajectory filtering, non-image data

**Comment by ailingzengzzz** [comment]
Hi @jiejiangd,

In theory, SmoothNet can refine any information with the input shape [T, C] and output the same shape, where T is the temporal (window size) length (e.g., T is 32) and C is the spatial dimension (C >=1). 
If you want to use the pre-trained models directly, please make sure the input values are normalized in [-1,1]. 
Since there may be different domains, you'd better train on your data with SmoothNet. Look forward to your feedback!

**Comment by jiejiangd** [comment]
Do I have any parameters to change when I only have one feature point per frame? So far there's no problem with losses going down in training, but in testing it's all zeros or Nans in each epoch.Thanks
