### ISSUE TITLE
滤波后在原图可视化骨骼图 贴合效果不理想？

### ISSUE THREAD

**Issue by codylcs** [cure-lab/SmoothNet#32]
曾爱玲 大佬您好，针对2D pose滤波，根据图像大小归一化图像序列对应的pose到【-1，1】，smoonthNet滤波后反归一化，整体的棍图看着是平滑没那么抖动了，但是在原视频中可视化，发现贴合到人的骨骼效果并不理想，可以简单分析下可能的原因吗？感谢

**Comment by ailingzengzzz** [comment]
Hi @codylcs,

Since SmoothNet provided models are trained on existing mocap data and it does not refer to the input image, it will happen positional shift when the distribution of your data movements differs significantly from the distribution of the original training data (e.g., quite different speeds).
