### ISSUE TITLE
Can i use SmoothNet to inference in realtime video?

### ISSUE THREAD

**Issue by Koruvika** [cure-lab/SmoothNet#48]

**Comment by HospitableHost** [comment]
Personally, I think it won't work. If you choose a model with a window size of 8, and if you want to process the i-th frame, you need to delay 7 frames to calculate the smoothed result of the i-th frame. So if fps is 25, you have to delay 7/25= 0.28s.

**Comment by ailingzengzzz** [comment]
Hi @Koruvika,

SmoothNet is a sliding-window-based model instead of an autoregressive model. It will delay for the first {i-1} frames. After the input length is larger than the window size i, you can smooth the i_{th} pose. However, it will suffer from inferior results than our original sliding window setting.  
A learning-based real-time model for smoothing would be an interesting direction.

**Comment by Koruvika** [comment]
Thanks for reply @HospitableHost  and @ailingzengzzz. Is there any smoothing method capable of doing real time?

**Comment by ailingzengzzz** [comment]
Hi @Koruvika ,

[One Euro](https://github.com/jaantollander/OneEuroFilter) is a real-time filter. [https://github.com/jaantollander/OneEuroFilter
